[package]
name = "unity_extract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tar = "0.4.40"
flate2 = "1.0.27"
clap = { version = "4.4.6", features = ["derive"] }
